install: 0

composer: 1
composer_home: ~

settings:

server_ini:
    hhvm.server.host: 127.0.0.1
    hhvm.server.port: 9000
    hhvm.log.use_log_file: true
    hhvm.log.file: /var/log/hhvm/error.log

php_ini:
    display_errors: On
    error_reporting: -1
    date.timezone: UTC
