target: ~

vm:
    provider:
        linode:
            distribution: Ubuntu 14.04 LTS
            datacenter: Newark
            plan: 1024
            token: LINODE_API_KEY
            ssh_key_name: Vagrant
    synced_folder:
        -
            source: ./
            target: /var/www
            id: webroot
            nfs: false
    network:
    provision:
        puppet:
            manifests_path: "puphpet/puppet/manifests"
            module_path: "puphpet/puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
ssh:
    username: PRIVATE_KEY_USER
    forward_agent: true
    private_key_path: "~/.ssh/id_rsa"
