puphpet.vagrantfile_linode.homepage:
    pattern:  /
    defaults: { _controller: PuphpetMainBundle:VagrantfileLinode:index }

puphpet.vagrantfile_linode.machine:
    pattern: /machine
    defaults: { _controller: PuphpetMainBundle:VagrantfileLinode:machine }

puphpet.vagrantfile_linode.synced_folder:
    pattern: /synced-folder
    defaults: { _controller: PuphpetMainBundle:VagrantfileLinode:syncedFolder }
