install: 1

settings:
    version: 7.2

modules:
    php:
        - cli
        - intl
        - xml
    pecl: []

ini:
    display_errors: On
    error_reporting: -1
    session.save_path: '/var/lib/php/session'
    date.timezone: UTC

fpm_ini:
    error_log: /var/log/php-fpm.log

fpm_pools:
    -
        ini:
            prefix: www
            listen: '127.0.0.1:9000'
            security.limit_extensions: '.php'
            user: www-user
            group: www-data

composer_home: ~
