# we actually need both environments PHP and rvm
# however it is only possible to define the environment for one language
language: php
rvm: 1.9.3
php:
  - 5.5

notifications:
  email:
    - jtreminio@gmail.com
env:
  - PUPPET_VERSION=3.4.3

install:
  - composer install

# PHPUnit tests only, rake spec could not be done within the same travis worker
# (ruby is installed on a PHP worker but .gemfile will be ignored)
script: php vendor/phpunit/phpunit/phpunit.php --coverage-text --configuration phpunit_ci.xml.dist

# whitelist
branches:
  only:
    - master
    - travis
    - spec
