install: 1

modules:
    php:
        - cli
        - intl
        - mcrypt
    pecl:
        - pecl_http

ini:
    display_errors: On
    error_reporting: -1
    session.save_path: "/var/lib/php/session"

timezone: America/Chicago

composer_home: ~
