parameters:

services:
    puphpet.extension.php.configure:
        class: Puphpet\Extension\PhpBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.php.front_controller:
        class: Puphpet\Extension\PhpBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.php.manifest_controller:
        class: Puphpet\Extension\PhpBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
