versions:
    - 5.6
    - 5.5

privileges:
    "Give all":
        - ALL
    "or, Give some":
        - ALTER
        - ALTER ROUTINE
        - CREATE
        - CREATE ROUTINE
        - CREATE TABLESPACE
        - CREATE TEMPORARY TABLES
        - CREATE USER
        - CREATE VIEW
        - DELETE
        - DROP
        - EVENT
        - EXECUTE
        - FILE
        - GRANT OPTION
        - INDEX
        - INSERT
        - LOCK TABLES
        - PROCESS
        - PROXY
        - REFERENCES
        - RELOAD
        - REPLICATION CLIENT
        - REPLICATION SLAVE
        - SELECT
        - SHOW DATABASES
        - SHOW VIEW
        - SHUTDOWN
        - SUPER
        - TRIGGER
        - UPDATE
        - USAGE

empty_user:
    name: ~
    password: ~

empty_database:
    name: ~
    sql: ~

empty_grant:
    user: ~
    table: '*.*'
    privileges:
        - ALL
