install: 0

settings:
    version: 5.5
    override_options: {}

users:
    -
        name: dbuser
        password: 123

databases:
    -
        name: dbname
        sql: ~

grants:
    -
        user: dbuser
        table: '*.*'
        privileges:
            - ALL
