empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: false

available_images:
    -
        image: b279d8e6-1cbd-4e7c-875a-f6dbffc4c4a0
        long_name: Debian Wheezy 7 x64 (PVHVM)
        php_versions:
            - 5.6
            - 5.5
            - 5.4
            - HHVM
    -
        image: a3ba4cf5-70b9-4805-afa2-30d1ab81a625
        long_name: Ubuntu Trusty 14.04 LTS x64
        php_versions:
            - 5.6
            - 5.5
            - HHVM
    -
        image: 598a4282-f14b-4e50-af4c-b3e52749d9f9
        long_name: Ubuntu Trusty 14.04 LTS x64 (PVHVM)
        php_versions:
            - 5.6
            - 5.5
            - HHVM
    -
        image: cca73d10-8953-4949-a2f2-1e5444a4130d
        long_name: Ubuntu Precise 12.04 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        image: a3da5530-71c6-4405-b64f-fd2da99d303c
        long_name: Ubuntu Precise 12.04 x64 (PVHVM)
        php_versions:
            - 5.5
            - 5.4
            - HHVM

available_sizes:
    - 512MB Standard Instance
    - 1GB Standard Instance
    - 2GB Standard Instance
    - 4GB Standard Instance
    - 8GB Standard Instance
    - 15GB Standard Instance
    - 30GB Standard Instance
    - 1 GB General Purpose v1
    - 2 GB General Purpose v1
    - 4 GB General Purpose v1
    - 8 GB General Purpose v1
    - 15 GB I/O v1
    - 30 GB I/O v1
    - 60 GB I/O v1
    - 90 GB I/O v1
    - 120 GB I/O v1

available_regions:
    dfw: Dallas (DFW)
    ord: Chicago (ORD)
    iad: Northern Virginia (IAD)
    syd: Sydney (SYD)
    lon: London (LON)
