empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: false

available_images:
    -
        image: Wheezy
        long_name: Debian Wheezy 7 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        image: Trusty
        long_name: Ubuntu Trusty 14.04 LTS x64
        php_versions:
            - 5.5
            - HHVM
    -
        image: Precise
        long_name: Ubuntu Precise 12.04 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM

available_sizes:
    - 512MB Standard Instance
    - 1GB Standard Instance
    - 2GB Standard Instance
    - 4GB Standard Instance
    - 8GB Standard Instance
    - 15GB Standard Instance
    - 30GB Standard Instance
    - 1 GB Performance
    - 2 GB Performance
    - 4 GB Performance
    - 8 GB Performance
    - 120 GB Performance
    - 15 GB Performance
    - 30 GB Performance
    - 60 GB Performance
    - 90 GB Performance

available_regions:
    dfw: Dallas (DFW)
    ord: Chicago (ORD)
    iad: Northern Virginia (IAD)
    syd: Sydney (SYD)
    lon: London (LON)
