empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: false

available_images:
    -
        image: Wheezy
        long_name: Debian Wheezy 7 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        image: Squeeze
        long_name: Debian Squeeze 6.06 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: Raring
        long_name: Ubuntu Raring 13.04 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        image: Quantal
        long_name: Ubuntu Quantal 12.10 x64
        php_versions:
            - 5.5
            - 5.4
    -
        image: Precise
        long_name: Ubuntu Precise 12.04 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM

available_sizes:
    - 512MB
    - 1GB
    - 2GB
    - 4GB
    - 8GB
    - 15GB
    - 30GB

available_regions:
    dfw: Dallas (DFW)
    ord: Chicago (ORD)
    iad: Northern Virginia (IAD)
    syd: Sydney (SYD)
    lon: London (LON)
