target: ~

vm:
    hostname: softlayer-server
    provider:
        softlayer:
            username: SOFTLAYER_USERNAME
            api_key: SOFTLAYER_API_KEY
            ssh_key: SOFTLAYER SAVED PUBLIC KEY NAME
            operating_system: UBUNTU_14_64
            datacenter: DAL01
            max_memory: 1024
            start_cpus: 1
            domain: test.com
    synced_folder:
        -
            source: ./
            target: /var/www
            id: webroot
            nfs: false
    provision:
        puppet:
            manifests_path: "puphpet/puppet/manifests"
            module_path: "puphpet/puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
ssh:
    username: PRIVATE_KEY_USER
    forward_agent: true
    private_key_path: "~/.ssh/id_rsa"
    public_key_path: "~/.ssh/id_rsa.pub"
