puphpet.main:
    resource: "@PuphpetMainBundle/Resources/config/routing.yml"
    prefix:   /

puphpet.extension.vagrantfilelocal:
    resource: "@PuphpetExtensionVagrantfileLocalBundle/Resources/config/routing.yml"
    prefix:   /extension/vagrantfile/local

puphpet.extension.vagrantfile.digital_ocean:
    resource: "@PuphpetExtensionVagrantfileDigitalOceanBundle/Resources/config/routing.yml"
    prefix:   /extension/vagrantfile/digitalocean

puphpet.extension.vagrantfile.rackspace:
    resource: "@PuphpetExtensionVagrantfileRackspaceBundle/Resources/config/routing.yml"
    prefix:   /extension/vagrantfile/rackspace

puphpet.extension.vagrantfile.aws:
    resource: "@PuphpetExtensionVagrantfileAwsBundle/Resources/config/routing.yml"
    prefix:   /extension/vagrantfile/aws

puphpet.extension.server:
    resource: "@PuphpetExtensionServerBundle/Resources/config/routing.yml"
    prefix:   /extension/server

puphpet.extension.apache:
    resource: "@PuphpetExtensionApacheBundle/Resources/config/routing.yml"
    prefix:   /extension/apache

puphpet.extension.nginx:
    resource: "@PuphpetExtensionNginxBundle/Resources/config/routing.yml"
    prefix:   /extension/nginx

puphpet.extension.php:
    resource: "@PuphpetExtensionPhpBundle/Resources/config/routing.yml"
    prefix:   /extension/php

puphpet.extension.hhvm:
    resource: "@PuphpetExtensionHhvmBundle/Resources/config/routing.yml"
    prefix:   /extension/hhvm

puphpet.extension.xdebug:
    resource: "@PuphpetExtensionXdebugBundle/Resources/config/routing.yml"
    prefix:   /extension/xdebug

puphpet.extension.xhprof:
    resource: "@PuphpetExtensionXhprofBundle/Resources/config/routing.yml"
    prefix:   /extension/xhprof

puphpet.extension.mysql:
    resource: "@PuphpetExtensionMysqlBundle/Resources/config/routing.yml"
    prefix:   /extension/mysql

puphpet.extension.postgresql:
    resource: "@PuphpetExtensionPostgresqlBundle/Resources/config/routing.yml"
    prefix:   /extension/postgresql

puphpet.extension.mariadb:
    resource: "@PuphpetExtensionMariaDbBundle/Resources/config/routing.yml"
    prefix:   /extension/mariadb

puphpet.extension.mongodb:
    resource: "@PuphpetExtensionMongoDbBundle/Resources/config/routing.yml"
    prefix:   /extension/mongodb

puphpet.extension.beanstalkd:
    resource: "@PuphpetExtensionBeanstalkdBundle/Resources/config/routing.yml"
    prefix:   /extension/beanstalkd

puphpet.extension.rabbitmq:
    resource: "@PuphpetExtensionRabbitMQBundle/Resources/config/routing.yml"
    prefix:   /extension/rabbitmq

puphpet.extension.elastic-search:
    resource: "@PuphpetExtensionElasticSearchBundle/Resources/config/routing.yml"
    prefix:   /extension/elastic-search

puphpet.extension.mailcatcher:
    resource: "@PuphpetExtensionMailCatcherBundle/Resources/config/routing.yml"
    prefix:   /extension/mailcatcher

puphpet.extension.redis:
    resource: "@PuphpetExtensionRedisBundle/Resources/config/routing.yml"
    prefix:   /extension/redis

puphpet.extension.firewall:
    resource: "@PuphpetExtensionFirewallBundle/Resources/config/routing.yml"
    prefix:   /extension/firewall

