empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: false

available_images:
    -
        image: CentOS 6.5 x64
        long_name: CentOS 6.5 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        image: Debian 7.0 x64
        long_name: Debian Wheezy 7.0 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        image: Ubuntu 14.04 x64
        long_name: Ubuntu Trusty 14.04 LTS x64
        php_versions:
            - 5.5
            - HHVM
    -
        image: Ubuntu 12.04.4 x64
        long_name: Ubuntu Precise 12.04 LTS x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM

available_sizes:
    512mb: 512MB / 1 CPU / 20GB SSD DISK / 1TB TRANSFER
    1gb: 1GB / 1 CPU / 30GB SSD DISK / 2TB TRANSFER
    2gb: 2GB / 2 CPUS / 40GB SSD DISK / 3TB TRANSFER
    4gb: 4GB / 2 CPUS / 60GB SSD DISK / 4TB TRANSFER
    8gb: 8GB / 4 CPUS / 80GB SSD DISK / 5TB TRANSFER
    16gb: 16GB / 8 CPUS / 160GB SSD DISK / 6TB TRANSFER
    32gb: 32GB / 12 CPUS / 320GB SSD DISK / 7TB TRANSFER
    48gb: 48GB / 16 CPUS / 480GB SSD DISK / 8TB TRANSFER
    64gb: 64GB / 20 CPUS / 640GB SSD DISK / 9TB TRANSFER

available_regions:
    nyc1: New York 1
    nyc2: New York 2
    sfo1: San Francisco 1
    ams2: Amsterdam 1
    ams2: Amsterdam 2
    sgp1: Singapore 1
    lon1: London 1
