vm:
    provider:
        digital_ocean:
            image: debian-7-0-x64
            region: New York 1
            size: 1GB
            token: DIGITAL_OCEAN_TOKEN
            ssh_key_name: Vagrant
    synced_folder:
        -
            source: ./
            target: /var/www
            id: webroot
            nfs: false
    network:
    provision:
        puppet:
            manifests_path: "puphpet/puppet"
            manifest_file: "site.pp"
            module_path: "puphpet/puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
                - "--parser future"
ssh:
    username: PRIVATE_KEY_USER
    forward_agent: true
    private_key_path: "~/.ssh/id_rsa"
