parameters:

services:
    puphpet.extension.vagrantfile.digital_ocean.configure:
        class: Puphpet\Extension\VagrantfileDigitalOceanBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.vagrantfile.digital_ocean.front_controller:
        class: Puphpet\Extension\VagrantfileDigitalOceanBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.vagrantfile.digital_ocean.manifest_controller:
        class: Puphpet\Extension\VagrantfileDigitalOceanBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
