empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: false

available_images:
#  Zone 3 France Direct Routing (Z03-R0-IKDC01-FR)
    'Zone 3 France Direct Routing (Z03-R0-IKDC01-FR)':
        -
            template_name: Ubuntu 14.04 - Server - 64bits
            os: linux
            name: Ubuntu 14.04 - Server - 64bits
            ssh_username: root
            php_versions:
                - 5.6
                - 5.5
                - 5.4
                - HHVM

available_service_offering_names:
    t1.pico: 0.5 vCPUs, 0.512 GiB memory, 50 GiB
    t1.micro:  1 vCPUs, 1 GiB memory, 100 GiB
    m1.small:  1 vCPUs, 1.7 GiB memory, 100 GiB
    m1.medium:  2 vCPUs, 3.75 GiB memory, 100 GiB
    m1.large:  4 vCPUs, 7.5 GiB memory, 100 GiB
    m1.extralarge: 8 vCPUs, 15 GiB memory, 100 GiB

available_zone_names:
    'Zone 3 France Direct Routing (Z03-R0-IKDC01-FR)': 'Zone 3 France Direct Routing (Z03-R0-IKDC01-FR)'
