available_privileges:
    "Give all":
        - ALL
    "or, Give some":
        - ALTER
        - CREATE
        - CREATE TEMPORARY TABLES
        - DELETE
        - DROP
        - EXECUTE
        - FILE
        - INDEX
        - INSERT
        - LOCAL TABLES
        - PROCESS
        - REFERENCES
        - RELOAD
        - REPLICATION CLIENT
        - REPLICATION SLAVE
        - SELECT
        - SHOW DATABASES
        - SHUTDOWN
        - SUPER
        - UPDATE
        - USAGE
        - GRANT OPTION

empty_database:
    name: ~
    user: ~
    password: ~
    host: localhost
    grant: []
    sql_file: ~
