parameters:

services:
    puphpet.extension.mysql.configure:
        class: Puphpet\Extension\MysqlBundle\Configure
        arguments:
            - "@service_container"

    puphpet.extension.mysql.front_controller:
        class: Puphpet\Extension\MysqlBundle\Controller\FrontController
        calls:
            - [ setContainer, [@service_container] ]

    puphpet.extension.mysql.manifest_controller:
        class: Puphpet\Extension\MysqlBundle\Controller\ManifestController
        calls:
            - [ setContainer, [@service_container] ]
