puphpet.main.homepage:
    path:  /
    defaults: { _controller: PuphpetBundle:Front:index }

puphpet.main.upload_config:
    path:  /upload-config
    defaults: { _controller: PuphpetBundle:Front:uploadConfig }

puphpet.main.generate_archive:
    path:  /generate-archive
    defaults: { _controller: PuphpetBundle:Front:generateArchive }

puphpet.main.generate_config:
    path:  /generate-config
    defaults: { _controller: PuphpetBundle:Front:generateConfig }

puphpet.main.download_puppet_modules:
    path:  /download-puppet-modules
    defaults: { _controller: PuphpetBundle:Front:downloadPuppetModules }

puphpet.main.about:
    path:  /about
    defaults: { _controller: PuphpetBundle:Front:about }

puphpet.main.help:
    path:  /help
    defaults: { _controller: PuphpetBundle:Front:help }

puphpet.main.github_btn:
    path:  /github-btn
    defaults: { _controller: PuphpetBundle:Front:githubBtn }

# deploy target
puphpet.vagrantfile_local:
    resource: "@PuphpetBundle/Resources/config/vagrantfile-local/routing.yml"
    prefix:   /extension/vagrantfile-local
puphpet.vagrantfile_rackspace:
    resource: "@PuphpetBundle/Resources/config/vagrantfile-rackspace/routing.yml"
    prefix:   /extension/vagrantfile-rackspace
puphpet.vagrantfile_linode:
    resource: "@PuphpetBundle/Resources/config/vagrantfile-linode/routing.yml"
    prefix:   /extension/vagrantfile-linode
puphpet.vagrantfile_softlayer:
    resource: "@PuphpetBundle/Resources/config/vagrantfile-softlayer/routing.yml"
    prefix:   /extension/vagrantfile-softlayer
puphpet.vagrantfile_aws:
    resource: "@PuphpetBundle/Resources/config/vagrantfile-aws/routing.yml"
    prefix:   /extension/vagrantfile-aws
puphpet.vagrantfile_gce:
    resource: "@PuphpetBundle/Resources/config/vagrantfile-gce/routing.yml"
    prefix:   /extension/vagrantfile-gce
puphpet.vagrantfile_digitalocean:
    resource: "@PuphpetBundle/Resources/config/vagrantfile-digitalocean/routing.yml"
    prefix:   /extension/vagrantfile-digitalocean

# system
puphpet.server:
    resource: "@PuphpetBundle/Resources/config/server/routing.yml"
    prefix:   /extension/server
puphpet.users_groups:
    resource: "@PuphpetBundle/Resources/config/users-groups/routing.yml"
    prefix:   /extension/users-groups
puphpet.locale:
    resource: "@PuphpetBundle/Resources/config/locale/routing.yml"
    prefix:   /extension/locale
puphpet.firewall:
    resource: "@PuphpetBundle/Resources/config/firewall/routing.yml"
    prefix:   /extension/firewall
puphpet.cron:
    resource: "@PuphpetBundle/Resources/config/cron/routing.yml"
    prefix:   /extension/cron

# web server
puphpet.nginx:
    resource: "@PuphpetBundle/Resources/config/nginx/routing.yml"
    prefix:   /extension/nginx
puphpet.apache:
    resource: "@PuphpetBundle/Resources/config/apache/routing.yml"
    prefix:   /extension/apache
puphpet.letsencrypt:
    resource: "@PuphpetBundle/Resources/config/letsencrypt/routing.yml"
    prefix:   /extension/letsencrypt

# language
puphpet.php:
    resource: "@PuphpetBundle/Resources/config/php/routing.yml"
    prefix:   /extension/php
puphpet.ruby:
    resource: "@PuphpetBundle/Resources/config/ruby/routing.yml"
    prefix:   /extension/ruby
puphpet.python:
    resource: "@PuphpetBundle/Resources/config/python/routing.yml"
    prefix:   /extension/python
puphpet.nodejs:
    resource: "@PuphpetBundle/Resources/config/nodejs/routing.yml"
    prefix:   /extension/nodejs
puphpet.hhvm:
    resource: "@PuphpetBundle/Resources/config/hhvm/routing.yml"
    prefix:   /extension/hhvm

# database
puphpet.mysql:
    resource: "@PuphpetBundle/Resources/config/mysql/routing.yml"
    prefix:   /extension/mysql
puphpet.mariadb:
    resource: "@PuphpetBundle/Resources/config/mariadb/routing.yml"
    prefix:   /extension/mariadb
puphpet.postgresql:
    resource: "@PuphpetBundle/Resources/config/postgresql/routing.yml"
    prefix:   /extension/postgresql
puphpet.mongodb:
    resource: "@PuphpetBundle/Resources/config/mongodb/routing.yml"
    prefix:   /extension/mongodb
puphpet.redis:
    resource: "@PuphpetBundle/Resources/config/redis/routing.yml"
    prefix:   /extension/redis
puphpet.sqlite:
    resource: "@PuphpetBundle/Resources/config/sqlite/routing.yml"
    prefix:   /extension/sqlite

# mail
puphpet.mailhog:
    resource: "@PuphpetBundle/Resources/config/mailhog/routing.yml"
    prefix:   /extension/mailhog

# work queue
puphpet.beanstalkd:
    resource: "@PuphpetBundle/Resources/config/beanstalkd/routing.yml"
    prefix:   /extension/beanstalkd
puphpet.rabbitmq:
    resource: "@PuphpetBundle/Resources/config/rabbitmq/routing.yml"
    prefix:   /extension/rabbitmq

# search server
puphpet.elastic_search:
    resource: "@PuphpetBundle/Resources/config/elastic-search/routing.yml"
    prefix:   /extension/elastic-search
puphpet.solr:
    resource: "@PuphpetBundle/Resources/config/solr/routing.yml"
    prefix:   /extension/solr
