install: 0

vhosts:
    -
        server_name: awesome.dev
        server_aliases:
            - www.awesome.dev
        www_root: /var/www/awesome.dev
        listen_port: 80
        envvars:
            - APP_ENV dev
        index_files:
            - index.html
            - index.htm
            - index.php
