install: 0

settings:
    default_vhost: 1
    proxy_buffers: 4 256k
    proxy_buffer_size: 128k

upstreams: []

vhosts:
    -
        server_name: awesome.dev
        server_aliases:
            - www.awesome.dev
        www_root: /var/www/awesome
        proxy: ''
        listen_port: 80
        ssl: false
        ssl_port: 443
        ssl_cert: ''
        ssl_key: ''
        rewrite_to_https: 0
        spdy: 0
        index_files:
            - index.html
            - index.htm
            - index.php
        client_max_body_size: '1m'
        locations:
            -
                location: '/'
                try_files:
                    - '$uri'
                    - '$uri/'
                    - 'index.php'
                fastcgi: ~
                fastcgi_index: ~
                fastcgi_split_path: ~
                fast_cgi_params_extra: []
            -
                location: '~ \.php$'
                try_files:
                    - '$uri'
                    - '$uri/'
                    - 'index.php'
                    - '/index.php$is_args$args'
                fastcgi: 127.0.0.1:9000
                fastcgi_index: index.php
                fastcgi_split_path: '^(.+\.php)(/.*)$'
                fast_cgi_params_extra:
                    - 'SCRIPT_FILENAME $request_filename'
                    - 'APP_ENV dev'
