install: 1

settings:
    version: "10.1.9"
    override_options: {}

users:
    -
        name: dbuser
        password: 123

databases:
    -
        name: dbname
        sql: ~

grants:
    -
        user: dbuser
        table: '*.*'
        privileges:
            - ALL
