empty_synced_folder:
    source: ~
    target: ~
    id: ~
    nfs: false

available_images:
# US East (Northern Virginia) Region
    us-east-1:
        -
            ami: ami-4b124a22
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-a73264ce
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM
# US West (Northern California) Region
    us-west-1:
        -
            ami: ami-80487ec5
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-acf9cde9
            os: ubuntu
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM
# US West (Northern California) Region
    us-west-2:
        -
            ami: ami-a850c898
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-6aad335a
            os: ubuntu
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM
# EU (Ireland) Region
    eu-west-1:
        -
            ami: ami-e34dae94
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-8e987ef9
            os: ubuntu
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM
# South America (Sao Paulo) Region
    sa-east-1:
        -
            ami: ami-8b6cca96
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-35258228
            os: ubuntu
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM
# Asia Pacific (Tokyo) Region
    ap-northeast-1:
        -
            ami: ami-914f2a90
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-3f32ac3e
            os: ubuntu
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM
# Asia Pacific (Singapore) Region
    ap-southeast-1:
        -
            ami: ami-687d283a
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-b84e04ea
            os: ubuntu
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM
# Asia Pacific (Sydney) Region
    ap-southeast-2:
        -
            ami: ami-9d4fd3a7
            os: debian
            name: Debian 7.1a x64 EBS
            ssh_username: admin
            php_versions:
                - 5.5
                - 5.4
                - HHVM
        -
            ami: ami-3d128f07
            os: ubuntu
            name: Ubuntu Precise 12.04.3 x64 EBS
            ssh_username: ubuntu
            php_versions:
                - 5.5
                - 5.4
                - HHVM

available_instance_types:
    t1.micro: up to 2 ECUs, 1 vCPUs, 0.613 GiB memory, EBS only
    m1.small: 1 ECUs, 1 vCPUs, 1.7 GiB memory, 1 x 160 GiB Storage Capacity
    m1.medium: 2 ECUs, 1 vCPUs, 3.7 GiB memory, 1 x 410 GiB Storage Capacity
    m1.large: 4 ECUs, 2 vCPUs, 7.5 GiB memory, 2 x 420 GiB Storage Capacity
    m1.xlarge: 8 ECUs, 4 vCPUs, 15 GiB memory, 4 x 420 GiB Storage Capacity
    m2.xlarge: 6.5 ECUs, 2 vCPUs, 17.1 GiB memory, 1 x 420 GiB Storage Capacity
    m2.2xlarge: 13 ECUs, 4 vCPUs, 34.2 GiB memory, 1 x 850 GiB Storage Capacity
    m2.4xlarge: 26 ECUs, 8 vCPUs, 68.4 GiB memory, 2 x 840 GiB Storage Capacity
    hi1.4xlarge: 35 ECUs, 16 vCPUs, 60.5 GiB memory, 2 x 1024 GiB Storage Capacity
    hs1.8xlarge: 35 ECUs, 16 vCPUs, 117 GiB memory, 24 x 2048 GiB Storage Capacity
    c1.medium: 5 ECUs, 2 vCPUs, 1.7 GiB memory, 1 x 350 GiB Storage Capacity
    c1.xlarge: 20 ECUs, 8 vCPUs, 7 GiB memory, 4 x 420 GiB Storage Capacity

available_regions:
    ap-northeast-1: Asia Pacific (Tokyo) Region
    ap-southeast-1: Asia Pacific (Singapore) Region
    ap-southeast-2: Asia Pacific (Sydney) Region
    eu-west-1: EU (Ireland) Region
    sa-east-1: South America (Sao Paulo) Region
    us-east-1: US East (Northern Virginia) Region
    us-west-1: US West (Northern California) Region
    us-west-2: US West (Oregon) Region
