vm:
    provider:
        aws:
            ami: ami-4b124a22
            region: us-east-1
            instance_type: m1.small
    synced_folder:
        -
            source: ./
            target: /var/www
            id: webroot
            nfs: false
    network:
    provision:
        puppet:
            manifests_path: "puphpet/puppet"
            manifest_file: "manifest.pp"
            module_path: "puphpet/puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
                - "--parser future"
ssh:
    username: admin
    forward_agent: true
    private_key_path: "~/.ssh/id_rsa"
