versions_deb:
    - 2.6.0
    - 2.6.1
    - 2.6.2
    - 2.6.3
    - 2.6.4
    - 2.6.5
    - 2.6.6
    - 2.6.7
    - 2.6.8
    - 2.6.9
    - 2.6.10
    - 2.6.11
    - 2.6.12

versions_rhel:
    - 2.6.0-1
    - 2.6.1-2
    - 2.6.2-1
    - 2.6.3-1
    - 2.6.4-1
    - 2.6.5-1
    - 2.6.6-1
    - 2.6.7-1
    - 2.6.8-1
    - 2.6.9-1
    - 2.6.10-1
    - 2.6.11-1
    - 2.6.12-1

empty_database:
    name: ~
    user: ~
    password: ~
