versions:
    - 3.6.2
    - 3.6.1
    - 3.6.0
    - 3.5.13
    - 3.5.12
    - 3.5.11
    - 3.5.10
    - 3.5.9
    - 3.5.8
    - 3.5.7
    - 3.5.6
    - 3.5.5
    - 3.5.4
    - 3.5.3
    - 3.5.2
    - 3.5.1
    - 3.4.10
    - 3.4.9
    - 3.4.8
    - 3.4.7
    - 3.4.6
    - 3.4.5
    - 3.4.4
    - 3.4.3
    - 3.4.2
    - 3.4.1
    - 3.4.0
    - 3.3.15
    - 3.3.14
    - 3.3.13
    - 3.3.12
    - 3.3.11
    - 3.3.10
    - 3.3.9
    - 3.3.8
    - 3.3.7
    - 3.3.6
    - 3.3.5
    - 3.3.4
    - 3.3.3
    - 3.3.2
    - 3.3.1
    - 3.3.0
    - 3.2.18
    - 3.2.17
    - 3.2.16
    - 3.2.15
    - 3.2.14
    - 3.2.13
    - 3.2.12
    - 3.2.11
    - 3.2.10
    - 3.2.9
    - 3.2.8
    - 3.2.7
    - 3.2.6
    - 3.2.5
    - 3.2.4
    - 3.2.3
    - 3.2.2
    - 3.2.1
    - 3.2.0

empty_database:
    name: ~
    user: ~
    password: ~
