target: ~

vm:
    provider:
        digitalocean:
            image: ~
            token: ~
            ssh_key_name: ~
            setup: true
            ipv6: false
            private_networking: false
            backups_enabled: false
            machines: [ ]
    provision:
        puppet:
            manifests_path: puphpet/puppet/manifests
            module_path:
                - puphpet/puppet/modules
                - puphpet/puppet/manifests
            options:
                - '--verbose'
                - '--hiera_config /opt/puphpet/puppet/hiera.yaml'
    synced_folder: [ ]
    post_up_message: ''
ssh:
    username: ~
    private_key_path: ~
    public_key_path: ~
