vm:
    box: softlayer
    hostname: master
    provider:
        softlayer:
            username: ~
            api_key: ~
            ssh_key: ~
            operating_system: ~
            datacenter: ~
            max_memory: ~
            start_cpus: ~
            domain: ~
    provision:
        puppet:
            manifests_path: "puphpet/puppet"
            manifest_file: "site.pp"
            module_path: "puphpet/puppet/modules"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
                - "--parser future"
    synced_folder: []

ssh:
    host: ~
    port: ~
    private_key_path: ~
    public_key_path: ~
    username: ~
    guest_port: ~
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: bash -l

vagrant:
    host: detect
