empty_vhost:
    servername: ~
    serveraliases: []
    docroot: ~
    port: 80
    setenv: []
    override: []
    options:
        - Indexes
        - FollowSymLinks
        - MultiViews
    custom_fragment: ~
    ssl: 0
    ssl_cert: ~
    ssl_key: ~
    ssl_chain: ~
    ssl_certs_dir: ~

available_modules:
    - cache
    - cgid
    - dav
    - dav_fs
    - deflate
    - disk_cache
    - expires
    - headers
    - info
    - ldap
    - mime_magic
    - php
    - proxy_ajp
    - proxy_balancer
    - proxy
    - rewrite
    - ssl
    - userdir
    - vhost_alias
