modules:
    - rewrite
    - php

vhosts:
    -
        servername: awesome.dev
        serveraliases:
            - www.awesome.dev
        docroot: /var/www/awesome
        port: 80
        setenv: # environment variables
            - APP_ENV dev
        override:
            - All

mod_pagespeed: true
mod_spdy: true
