empty_vhost:
    servername: ~
    serveraliases: []
    docroot: /var/www/REPLACE_ME
    port: 80
    setenvif:
        - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
    custom_fragment: []
    directories: []
    ssl: 0
    ssl_cert: ~
    ssl_key: ~
    ssl_chain: ~
    ssl_certs_dir: ~

empty_directory:
    provider: directory
    directoryindex: index.html
    path: /var/www/REPLACE_ME
    options:
        - Indexes
        - FollowSymlinks
        - MultiViews
    allow_override:
        - All
    require:
        - all granted
    custom_fragment: []

empty_files_match:
    provider: filesmatch
    path: '\.php$'
    sethandler: 'proxy:fcgi://127.0.0.1:9000'
    setenv: []
    custom_fragment: []

empty_rewrite:
    comment: ~
    rewrite_base: ~
    rewrite_cond: []
    rewrite_rule: []

pregenerated_directories:
    html:
        html:
            path: /var/www/REPLACE_ME
            directoryindex: index.html
            options:
                - Indexes
                - FollowSymlinks
                - MultiViews
            allow_override:
                - All
            require:
                - all granted
            provider: directory
    php:
        php_html:
            path: /var/www/REPLACE_ME
            directoryindex: index.php index.html
            options:
                - Indexes
                - FollowSymlinks
                - MultiViews
            allow_override:
                - All
            require:
                - all granted
            provider: directory
        php_php:
            path: \.php$
            sethandler: 'proxy:fcgi://127.0.0.1:9000'
            provider: filesmatch
    symfony2_3:
        sf2_3_fm:
            path: \.php$
            sethandler: 'proxy:fcgi://127.0.0.1:9000'
            setenv:
                - APP_ENV dev
            provider: filesmatch
        sf2_3_dir:
            path: /var/www/REPLACE_ME/web
            directoryindex: app.php
            setenv:
                - APP_ENV dev
            options:
                - Indexes
                - FollowSymlinks
                - MultiViews
            allow_override:
                - All
            require:
                - all granted
            provider: directory
            rewrites:
                rewrite_1:
                    rewrite_cond:
                        - '%{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$'
                    rewrite_rule:
                        - '^(.*) - [E=BASE:%1]'
                rewrite_2:
                    rewrite_cond:
                        - '%{ENV:REDIRECT_STATUS} ^$'
                    rewrite_rule:
                        - '^app\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]'
                rewrite_3:
                    rewrite_cond:
                        - '%{REQUEST_FILENAME} -f'
                    rewrite_rule:
                        - '.? - [L]'
                rewrite_4:
                    rewrite_rule:
                        - '.? %{ENV:BASE}/app.php [L]'
    symfony4:
        sf4_fm:
            path: \.php$
            sethandler: 'proxy:fcgi://127.0.0.1:9000'
            setenv:
                - APP_ENV dev
            provider: filesmatch
        sf4_dir:
            path: /var/www/REPLACE_ME/public
            directoryindex: index.php
            setenv:
                - APP_ENV dev
            options:
                - Indexes
                - FollowSymlinks
                - MultiViews
            allow_override:
                - All
            require:
                - all granted
            provider: directory
            rewrites:
                rewrite_1:
                    rewrite_cond:
                        - '%{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$'
                    rewrite_rule:
                        - '^(.*) - [E=BASE:%1]'
                rewrite_2:
                    rewrite_cond:
                        - '%{ENV:REDIRECT_STATUS} ^$'
                    rewrite_rule:
                        - '^index\.php(/(.*)|$) %{ENV:BASE}/$2 [R=301,L]'
                rewrite_3:
                    rewrite_cond:
                        - '%{REQUEST_FILENAME} -f'
                    rewrite_rule:
                        - '.? - [L]'
                rewrite_4:
                    rewrite_rule:
                        - '.? %{ENV:BASE}/index.php [L]'
    laravel:
        laravel_fm:
            path: \.php$
            sethandler: 'proxy:fcgi://127.0.0.1:9000'
            setenv:
                - APP_ENV dev
            provider: filesmatch
        laravel_dir:
            path: /var/www/REPLACE_ME/public
            directoryindex: index.php
            setenv:
                - APP_ENV dev
            options:
                - Indexes
                - FollowSymlinks
                - MultiViews
            allow_override:
                - All
            require:
                - all granted
            provider: directory

modules:
    - cache
    - cgid
    - dav
    - dav_fs
    - deflate
    - disk_cache
    - expires
    - headers
    - info
    - ldap
    - mime_magic
    - pagespeed
    - proxy_ajp
    - proxy_balancer
    - proxy_fcgi
    - proxy_http
    - proxy
    - rewrite
    - userdir
    - vhost_alias
