install: 0

settings:
    version: 2.4
    sendfile: 0

modules:
    - proxy_fcgi
    - rewrite

vhosts:
    -
        servername: awesome.dev
        serveraliases:
            - www.awesome.dev
        docroot: /var/www/awesome/web
        port: 80
        setenvif:
            - 'Authorization "(.*)" HTTP_AUTHORIZATION=$1'
        custom_fragment: ~
        directories:
            -
                provider: directory
                path: /var/www/awesome/web
                directoryindex: app.dev
                options:
                    - Indexes
                    - FollowSymlinks
                    - MultiViews
                allow_override:
                    - All
                require:
                    - all granted
                custom_fragment: ''
        files_match:
            -
                provider: filesmatch
                path: '(app_dev|config)\.php$'
                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                setenv:
                    - APP_ENV dev
                custom_fragment: ''
            -
                provider: filesmatch
                path: '(app)\.php$'
                sethandler: 'proxy:fcgi://127.0.0.1:9000'
                setenv:
                    - APP_ENV prod
                custom_fragment: ''
        ssl: 0
        ssl_cert: ~
        ssl_key: ~
        ssl_chain: ~
        ssl_certs_dir: ~
        ssl_protocol: ~
        ssl_cipher: ~
