target: local

vm:
    provider:
        local:
            box: puphpet/ubuntu1604-x64
            box_url: puphpet/ubuntu1604-x64
            box_version: 0
            chosen_virtualizer: virtualbox
            virtualizers:
                virtualbox:
                    modifyvm:
                        natdnshostresolver1: false
                    showgui: 0
                vmware:
                    numvcpus: 1
                parallels:
                    use_linked_clone: 0
                    check_guest_tools: 0
                    update_guest_tools: 0
            machines:
                -
                    id: machine1
                    hostname: machine1.puphpet
                    memory: 512
                    cpus: 1
                    network:
                        private_network: 192.168.56.101
                        forwarded_port:
                            -
                                guest: ~
                                host: ~
    provision:
        puppet:
            manifests_path: 'puphpet/puppet/manifests'
            module_path: 'puphpet/puppet/modules'
            options:
                - '--verbose'
                - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
    synced_folder:
        -
            id: vagrant-root
            source: ./
            target: /var/www
            sync_type: default
            owner: 'www-data'
            group: 'www-data'
            smb:
                smb_host: ~
                smb_username: ~
                smb_password: ~
                mount_options:
                    dir_mode: '0775'
                    file_mode: '0664'
            rsync:
                args:
                    - '--verbose'
                    - '--archive'
                    - '-z'
                exclude:
                    - '.vagrant/'
                    - '.git/'
                auto: true
    usable_port_range:
        start: 10200
        stop: 10500
    post_up_message: ''

ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: vagrant
    guest_port: ~
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: bash -l
    insert_key: false

vagrant:
    host: detect

proxy:
    http: ~
    https: ~
    ftp: ~
    no_proxy: ''
