versions:
    - 3.4.0
    - 3.3.5
    - 3.3.4
    - 3.3.3
    - 3.3.2
    - 3.3.1
    - 3.3.0
    - 3.2.5
    - 3.2.4
    - 3.2.3
    - 3.2.2
    - 3.2.1
    - 3.2
    - 3.1.5
    - 3.1.4
    - 3.1.3
    - 3.0.1
    - 2.7.6
    - 2.7.5
    - 2.7.4
    - 2.7.3
    - 2.7.2
    - 2.7.1
    - 2.7
    - 2.6.9
    - 2.6.8
    - 2.6.7
    - 2.6.6
    - 2.5.6
    - 2.5.5
    - 2.5.4
    - 2.5.3
    - 2.5.2
    - 2.5.1
    - 2.5
    - 2.4.6
    - 2.4.5
    - 2.4.4
    - 2.4.3
    - 2.4.2
    - 2.4.1
    - 2.4

empty_version:
    version: ~
    virtualenv: 0
