parameters:

services:
    randomlib:
        class: RandomLib\Factory

    puphpet.extension.manager:
        class: Puphpet\MainBundle\Extension\Manager
        arguments:
            - "@service_container"
        calls:
        # vagrantfile group
            - [ addExtensionToGroup, [ 'deploy-target', @puphpet.extension.vagrantfile.local.configure ] ]
            - [ addExtensionToGroup, [ 'deploy-target', @puphpet.extension.vagrantfile.digital_ocean.configure ] ]
            - [ addExtensionToGroup, [ 'deploy-target', @puphpet.extension.vagrantfile.rackspace.configure ] ]
            - [ addExtensionToGroup, [ 'deploy-target', @puphpet.extension.vagrantfile.aws.configure ] ]
        # server
            - [ addExtension, [ @puphpet.extension.server.configure ] ]
            - [ addExtensionToGroup, [ 'server-extensions', @puphpet.extension.mailcatcher.configure ] ]
        # firewall
            - [ addExtension, [ @puphpet.extension.firewall.configure ] ]
        # webserver group
            - [ addExtensionToGroup, [ 'webserver', @puphpet.extension.apache.configure ] ]
            - [ addExtensionToGroup, [ 'webserver', @puphpet.extension.nginx.configure ] ]
        # php / hhvm
            - [ addExtensionToGroup, [ 'php-engine', @puphpet.extension.php.configure ] ]
            - [ addExtensionToGroup, [ 'php-engine', @puphpet.extension.hhvm.configure ] ]
            - [ addExtensionToGroup, [ 'php-extensions', @puphpet.extension.xdebug.configure ] ]
            - [ addExtensionToGroup, [ 'php-extensions', @puphpet.extension.xhprof.configure ] ]
            - [ addExtensionToGroup, [ 'php-extensions', @puphpet.extension.drush.configure ] ]
        # database group
            - [ addExtensionToGroup, [ 'database', @puphpet.extension.mysql.configure ] ]
            - [ addExtensionToGroup, [ 'database', @puphpet.extension.postgresql.configure ] ]
            - [ addExtensionToGroup, [ 'database', @puphpet.extension.mariadb.configure ] ]
        # nosql db group
            - [ addExtensionToGroup, [ 'nosql', @puphpet.extension.mongodb.configure ] ]
            - [ addExtensionToGroup, [ 'nosql', @puphpet.extension.redis.configure ] ]
        # work queues
            - [ addExtensionToGroup, [ 'work-queue', @puphpet.extension.beanstalkd.configure ] ]
            - [ addExtensionToGroup, [ 'work-queue', @puphpet.extension.rabbitmq.configure ] ]
        # search servers
            - [ addExtensionToGroup, [ 'search-server', @puphpet.extension.elastic_search.configure ] ]

    puphpet.twig.base_extension:
        class: Puphpet\MainBundle\Twig\BaseExtension
        arguments:
            - "@randomlib"
        tags:
            - { name: twig.extension }
