parameters:
#    puphpet_main.example.class: Puphpet\MainBundle\Example

services:
    randomlib:
        class: RandomLib\Factory

    puphpet.extension.manager:
        class: Puphpet\MainBundle\Extension\Manager
        arguments:
            - "@service_container"
        calls:
            - [ addExtension, [ @puphpet.extension.vagrantfile.configure ] ]

    puphpet.twig.base_extension:
        class: Puphpet\MainBundle\Twig\BaseExtension
        arguments:
            - "@randomlib"
        tags:
            - { name: twig.extension }
