parameters:

services:
    randomlib:
        class: RandomLib\Factory

    puphpet.extension.manager:
        class: Puphpet\MainBundle\Extension\Manager
        arguments:
            - "@service_container"
        calls:
        # vagrantfile
            - [ addExtension, [ @puphpet.extension.vagrantfile.local.configure ] ]
            - [ addExtension, [ @puphpet.extension.vagrantfile.digital_ocean.configure ] ]
            - [ addExtension, [ @puphpet.extension.vagrantfile.rackspace.configure ] ]
            - [ addExtension, [ @puphpet.extension.vagrantfile.aws.configure ] ]
            - [ addExtension, [ @puphpet.extension.vagrantfile.gce.configure ] ]
        # server
            - [ addExtension, [ @puphpet.extension.server.configure ] ]
        # firewall
            - [ addExtension, [ @puphpet.extension.firewall.configure ] ]
        # webservers
            - [ addExtension, [ @puphpet.extension.apache.configure ] ]
            - [ addExtension, [ @puphpet.extension.nginx.configure ] ]
        # languages
            - [ addExtension, [ @puphpet.extension.php.configure ] ]
            - [ addExtension, [ @puphpet.extension.hhvm.configure ] ]
            - [ addExtensionToGroup, [ 'php-extensions', @puphpet.extension.xdebug.configure ] ]
            - [ addExtensionToGroup, [ 'php-extensions', @puphpet.extension.xhprof.configure ] ]
            - [ addExtensionToGroup, [ 'php-extensions', @puphpet.extension.drush.configure ] ]
            - [ addExtension, [ @puphpet.extension.ruby.configure ] ]
            - [ addExtension, [ @puphpet.extension.nodejs.configure ] ]
            - [ addExtension, [ @puphpet.extension.python.configure ] ]
        # databases
            - [ addExtension, [ @puphpet.extension.mysql.configure ] ]
            - [ addExtension, [ @puphpet.extension.postgresql.configure ] ]
            - [ addExtension, [ @puphpet.extension.mariadb.configure ] ]
            - [ addExtension, [ @puphpet.extension.sqlite.configure ] ]
            - [ addExtension, [ @puphpet.extension.mongodb.configure ] ]
            - [ addExtension, [ @puphpet.extension.redis.configure ] ]
        # additional tools
            - [ addExtension, [ @puphpet.extension.mailcatcher.configure ] ]
            - [ addExtension, [ @puphpet.extension.beanstalkd.configure ] ]
            - [ addExtension, [ @puphpet.extension.rabbitmq.configure ] ]
            - [ addExtension, [ @puphpet.extension.elastic_search.configure ] ]

    puphpet.twig.base_extension:
        class: Puphpet\MainBundle\Twig\BaseExtension
        arguments:
            - "@randomlib"
        tags:
            - { name: twig.extension }
