empty_synced_folder:
    source: ~
    target: ~
    id: vagrant-root
    nfs: 'false'

available_boxes:
    -
        url: puphpet/centos65-x64
        os: centos
        short_name: puphpet/centos65-x64
        long_name: CentOS 6.5 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/debian75-x64
        os: debian
        short_name: puphpet/debian75-x64
        long_name: Debian Wheezy 7.5 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/debian75-x32
        os: debian
        short_name: puphpet/debian75-x32
        long_name: Debian Wheezy 7.5 x32
        php_versions:
            - 5.5
            - 5.4
            - HHVM
    -
        url: puphpet/ubuntu1404-x64
        os: ubuntu
        short_name: puphpet/ubuntu1404-x64
        long_name: Ubuntu Precise 14.04 x64
        php_versions:
            - 5.5
            - HHVM
    -
        url: puphpet/ubuntu1204-x64
        os: ubuntu
        short_name: puphpet/ubuntu1204-x64
        long_name: Ubuntu Precise 12.04 x64
        php_versions:
            - 5.5
            - 5.4
            - HHVM
