vm:
    provider:
        virtualbox: []
    synced_folder:
        -
            source: ./
            target: /var/www
            id: vagrant-root
            sync_type: 'default'
            rsync:
                args:
                    - "--verbose"
                    - "--archive"
                    - "--delete"
                    - "-z"
                exclude:
                    - ".vagrant/"
                auto: true
    network:
        forwarded_port:
            -
                guest: ~
                host: ~
    provision:
        puppet:
            manifests_path: "puphpet/puppet"
            manifest_file: "manifest.pp"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/puphpet/puppet/hiera.yaml"
                - "--parser future"
ssh:
    forward_agent: true
